# basic configuration
baseURL = 'http://bp-dwh.de/'
copyright = '2023 Max Erler'
title = 'Bert Pollack Data Warehousing'
theme = 'hugo-developer-portfolio'


# language
languageCode = 'en-us'
defaultContentLanguage = 'de'
[languages]

    [languages.de]
        languageName = 'Deutsch'
        weight = 1

    [languages.en]
        languageName = 'English'
        weight = 2

        [languages.en.menu]

            [[languages.en.menu.main]]
            weight = 1
            name = "Imprint"

            [[languages.en.menu.main]]
            weight = 2
            name = "Privacy"

#            [[languages.en.menu.main]]
#            name = "Blog"

#            [[languages.en.menu.main]]
#            name = "Portfolio"

#            [[languages.en.menu.main]]
#            name = "Contact"

        [languages.en.params]
            home = "Home"
            # Meta data
            description = "Website of Bert Pollack. Specialist for Data Warehousing in Munich, Germany."
            author = "Bert Pollack"
            languageImage = '/images/flags/de.png'

            [languages.en.params.contact]
                enable = true
                formAction = "" #contact form works with formspree.io

            [languages.en.params.footer]
                email = "info@bp-dwh.de"
                address = "Geyerspergerstraße 44, 80689 Munich, Germany"
                googlemaps = "https://www.openstreetmap.org/node/2674983025"


# navigation
[menu]
    [[menu.main]]
    weight = 1
    name = "Impressum"

    [[menu.main]]
    weight = 2
    name = "Datenschutz"

#    [[menu.main]]
#    name = "Über mich"
#    URL = "about"
#    weight=1

#    [[menu.main]]
#    name = "Blog"
#    URL = "blog"
#    weight=3

#    [[menu.main]]
#    name = "Portfolio"
#    URL = "portfolio"
#    weight=2

#    [[menu.main]]
#    name = "Kontakt"
#    URL = "contact"
#    weight=4


[params]
home = "Startseite"
# Meta data
description = "Website von Bert Pollack. Spezialist für Data Warehousing in München, Deutschland."
author = "Bert Pollack"
languageImage = '/images/flags/en.png'

  [params.contact]
  enable = true
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "info@bp-dwh.de"
  address = "Geyerspergerstraße 44, 80689 München"
  googlemaps = "https://www.openstreetmap.org/node/2674983025"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4


# plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"